### ISSUE TITLE
Collection directive

### ISSUE THREAD

**Issue by cecillem** [Erol/ethos#17]
It would be nice to have a directive to define a collection, such as:
```
class BookShelf
  collection :books, :Book
end
```

Also, it would be nice to make the collection classes lazy loadable

**Comment by Erol** [comment]
Lazy evaluation of attribute classes would indeed be useful, and I'm more inclined to go with how Ohm does it - your example's approach - compared to AR.

I'm still not sure if we should do coercions when the collection array is mutated. [Virtus](https://github.com/solnic/virtus) doesn't seem to do it and suggests the introduction of a collection class. Taken from the Virtus README:

    # This will coerce Hash to a Book instance
    library.books = [ { :title => 'Introduction to Virtus' } ]

    # This WILL NOT COERCE the value because you mutate the books array with Array#<<
    library.books << { :title => 'Another Introduction to Virtus' }

But, I personally find this coercion use case interesting. There might be merit in implementing our own collection class which has built-in support for coercion.

**Comment by Erol** [comment]
More inclined now to go with class names as strings instead of symbols. It's more consistent when namespaces are considered:

```
class Person
  prepend Ethos::Entity

  attribute :name,    'String'
  attribute :address, 'Contact::Address'
  attribute :phone,   'Contact::Phone'
end
```

**Comment by Erol** [comment]
Read-only collections are now done via #24. Support for mutable collections are still pending.

**Comment by Erol** [comment]
Lazy evaluation of type classes has been done on #25.

**Comment by Erol** [comment]
Instead of rolling our own `#map` and other enumeration methods, it might be easier to just include `Enumerable` on `Ethos::Collection`.

**Comment by Erol** [comment]
Collections are finally enumerable thanks to #38.
