### ISSUE TITLE
Hash with indifferent access

### ISSUE THREAD

**Issue by cecillem** [Erol/ethos#18]
Dunno if I'm just using it wrong but I encountered something weird when I declared my entities as "symbols"
```
class AdminEntity
  prepend Ethos::Entity

  attribute :_id, String
end
```
Then I called it on a hash with keys that are not "symbolized"
```
admin = AdminEntity.new("_id" => "123")
```
I get a nil value
```
admin._id
=> nil
```
But when I do this
```
admin = AdminEntity.new(_id:  "123")
```
It works fine
```
admin._id
=> "123"
```

**Comment by Erol** [comment]
Fixed by #19.
